name: Test Unauthorized Repo

on: [push]
  

jobs:
  test:
    
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          echo "Running in unauthorized repository"
          sleep 30
